# Generated by Django 4.1.7 on 2023-03-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
