# Generated by Django 4.1.7 on 2023-03-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_first_name_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
