# Generated by Django 4.1.7 on 2023-03-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirm_password',
        ),
    ]
