# Generated by Django 4.1.7 on 2023-03-27 08:20

import auth_app.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_customuser_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(max_length=128, validators=[auth_app.validation.validate_password]),
        ),
    ]
