# Generated by Django 4.1.7 on 2023-03-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_passwordreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
